# Generated by Django 3.2.14 on 2022-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='address',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
