# Generated by Django 3.2.14 on 2022-10-27 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_marker_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.CreateModel(
            name='HelperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_count', models.IntegerField()),
                ('helper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_info_helper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
