# Generated by Django 3.2.14 on 2022-10-18 06:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_riview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riview',
            new_name='Review',
        ),
    ]
