# Generated by Django 3.2.14 on 2022-10-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221028_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperinfo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
