# Generated by Django 3.2.14 on 2022-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221019_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='todo_review',
            field=models.BooleanField(),
        ),
    ]
