# Generated by Django 3.2.14 on 2022-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221028_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
