# Generated by Django 3.2.14 on 2022-10-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_promise_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='promise',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='review_promise', to='api.promise'),
            preserve_default=False,
        ),
    ]
