# Generated by Django 3.2.14 on 2022-11-07 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_review_promise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateTimeField()),
                ('status', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
