# Generated by Django 3.2.14 on 2022-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221107_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatecode',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
