# Generated by Django 3.2.14 on 2022-09-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='send_user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='helper',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='sender_helper', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='teen',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='sender_teen', to='accounts.user'),
            preserve_default=False,
        ),
    ]
