# Generated by Django 3.2.14 on 2022-07-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Helper', '헬퍼'), ('Teen', '청소년')], default='Teen', max_length=10),
            preserve_default=False,
        ),
    ]
