# Generated by Django 3.2.14 on 2022-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificated',
            field=models.BooleanField(default=False),
        ),
    ]
